import type {
  AgentUser,
  AgentCase,
  CaseDetail,
  AgentMetrics,
  AgentSettings,
} from "@/lib/types/agent";

// ─── Agent User ───────────────────────────────────────────────────────────────

export const MOCK_AGENT_USER: AgentUser = {
  id: "agent-001",
  fullName: "Aline Mukamana",
  firstName: "Aline",
  initials: "AM",
  email: "aline.m@proxiserve.rw",
  role: "AGENT",
  city: "Kigali",
  availability: "available",
  dailyCap: 8,
  acceptNewCases: true,
};

// ─── All Cases (14 rows from today-queue.html) ────────────────────────────────

export const MOCK_CASES: AgentCase[] = [
  {
    code: "PRX-2026-00483",
    serviceName: "Passport renewal",
    serviceNameBase: "Passport",
    serviceNameItalic: "renewal",
    clientName: "Aline Kabera",
    clientInitials: "AK",
    status: "in-progress",
    priority: "high",
    ageDisplay: "3d 4h",
    slaState: "over",
    nextAction: "Review re-uploaded photo",
    fee: 15000,
    submittedAt: "19 May 2026",
    category: "Identity",
  },
  {
    code: "PRX-2026-00477",
    serviceName: "Business license",
    serviceNameBase: "Business",
    serviceNameItalic: "license",
    clientName: "Eric Niyomugabo",
    clientInitials: "EN",
    status: "action-required",
    priority: "high",
    ageDisplay: "2d 18h",
    slaState: "over",
    nextAction: "Verify company registration docs",
    fee: 45000,
    submittedAt: "20 May 2026",
    category: "Business",
  },
  {
    code: "PRX-2026-00491",
    serviceName: "Tax registration",
    serviceNameBase: "Tax",
    serviceNameItalic: "registration",
    clientName: "Marie Uwase",
    clientInitials: "MU",
    status: "action-required",
    priority: "high",
    ageDisplay: "1d 6h",
    slaState: "warn",
    nextAction: "Collect missing TIN form",
    fee: 12000,
    submittedAt: "21 May 2026",
    category: "Tax",
  },
  {
    code: "PRX-2026-00461",
    serviceName: "National ID",
    serviceNameBase: "National",
    serviceNameItalic: "ID",
    clientName: "Patrick Mugabo",
    clientInitials: "PM",
    status: "in-progress",
    priority: "mid",
    ageDisplay: "4d 2h",
    slaState: "warn",
    nextAction: "Submit to Irembo",
    fee: 8000,
    submittedAt: "18 May 2026",
    category: "Identity",
  },
  {
    code: "PRX-2026-00459",
    serviceName: "Driver's license",
    serviceNameBase: "Driver's",
    serviceNameItalic: "license",
    clientName: "Diane Ingabire",
    clientInitials: "DI",
    status: "in-progress",
    priority: "mid",
    ageDisplay: "3d 12h",
    slaState: "ok",
    nextAction: "Book driving test slot",
    fee: 18000,
    submittedAt: "17 May 2026",
    category: "Identity",
  },
  {
    code: "PRX-2026-00502",
    serviceName: "Mutuelle de Santé",
    serviceNameBase: "Mutuelle de",
    serviceNameItalic: "Santé",
    clientName: "Jean Habimana",
    clientInitials: "JH",
    status: "in-progress",
    priority: "mid",
    ageDisplay: "1d 8h",
    slaState: "ok",
    nextAction: "Verify income certificate",
    fee: 9000,
    submittedAt: "22 May 2026",
    category: "Health",
  },
  {
    code: "PRX-2026-00488",
    serviceName: "Birth certificate",
    serviceNameBase: "Birth",
    serviceNameItalic: "certificate",
    clientName: "Rose Mukeshimana",
    clientInitials: "RM",
    status: "in-progress",
    priority: "mid",
    ageDisplay: "2d 3h",
    slaState: "ok",
    nextAction: "Await Civil Registry confirmation",
    fee: 6000,
    submittedAt: "20 May 2026",
    category: "Identity",
  },
  {
    code: "PRX-2026-00474",
    serviceName: "Trading license",
    serviceNameBase: "Trading",
    serviceNameItalic: "license",
    clientName: "Claude Niyonzima",
    clientInitials: "CN",
    status: "awaiting-response",
    priority: "mid",
    ageDisplay: "5d 10h",
    slaState: "warn",
    nextAction: "Waiting for RDB approval",
    fee: 28000,
    submittedAt: "16 May 2026",
    category: "Business",
  },
  {
    code: "PRX-2026-00465",
    serviceName: "VAT registration",
    serviceNameBase: "VAT",
    serviceNameItalic: "registration",
    clientName: "Thierry Gasana",
    clientInitials: "TG",
    status: "awaiting-response",
    priority: "low",
    ageDisplay: "6d",
    slaState: "ok",
    nextAction: "Awaiting RRA confirmation",
    fee: 22000,
    submittedAt: "16 May 2026",
    category: "Tax",
  },
  {
    code: "PRX-2026-00503",
    serviceName: "Construction permit",
    serviceNameBase: "Construction",
    serviceNameItalic: "permit",
    clientName: "Olivier Byiringiro",
    clientInitials: "OB",
    status: "in-progress",
    priority: "low",
    ageDisplay: "22h",
    slaState: "ok",
    nextAction: "Upload site plan photos",
    fee: 38000,
    submittedAt: "22 May 2026",
    category: "Construction",
  },
  {
    code: "PRX-2026-00437",
    serviceName: "Passport renewal",
    serviceNameBase: "Passport",
    serviceNameItalic: "renewal",
    clientName: "Thierry Murenzi",
    clientInitials: "TM",
    status: "in-progress",
    priority: "low",
    ageDisplay: "8d",
    slaState: "ok",
    nextAction: "Collect renewed passport",
    fee: 15000,
    submittedAt: "14 May 2026",
    category: "Identity",
  },
  {
    code: "PRX-2026-00442",
    serviceName: "Company registration",
    serviceNameBase: "Company",
    serviceNameItalic: "registration",
    clientName: "Yvonne Nyiransengimana",
    clientInitials: "YN",
    status: "completed",
    priority: "low",
    ageDisplay: "9d",
    slaState: "ok",
    nextAction: "Delivered",
    fee: 42000,
    submittedAt: "13 May 2026",
    category: "Business",
  },
  {
    code: "PRX-2026-00449",
    serviceName: "National ID",
    serviceNameBase: "National",
    serviceNameItalic: "ID",
    clientName: "Felix Nkurunziza",
    clientInitials: "FN",
    status: "completed",
    priority: "low",
    ageDisplay: "10d",
    slaState: "ok",
    nextAction: "Collected by client",
    fee: 8000,
    submittedAt: "12 May 2026",
    category: "Identity",
  },
  {
    code: "PRX-2026-00452",
    serviceName: "Driver's license",
    serviceNameBase: "Driver's",
    serviceNameItalic: "license",
    clientName: "Sandrine Uwimana",
    clientInitials: "SU",
    status: "completed",
    priority: "low",
    ageDisplay: "11d",
    slaState: "ok",
    nextAction: "Collected by client",
    fee: 18000,
    submittedAt: "11 May 2026",
    category: "Identity",
  },
];

export const NEEDS_YOU_TODAY = MOCK_CASES.filter(
  (c) => c.slaState === "over" || c.priority === "high"
).slice(0, 3);

// ─── Case Detail (PRX-2026-00483) ─────────────────────────────────────────────

export const MOCK_CASE_DETAIL: CaseDetail = {
  ...MOCK_CASES[0],
  clientPhone: "+250 78 8 *** 456",
  clientNationalId: "1 1992 8 …31",
  clientLanguage: "EN",
  clientMemberSince: "Guest",
  clientOtherCases: "None",
  paymentStatus: "paid",
  paymentAmount: 15000,
  paymentMethod: "MTN MoMo",
  paymentDate: "23 May",
  slaTarget: "Over by 1d",
  turnaroundEst: "5–7 days",
  applicationAnswers: [
    { label: "Reason for renewal", value: "Expired" },
    { label: "Current passport no.", value: "PC284615" },
    { label: "Expiry date", value: "12 Aug 2026" },
    { label: "Place of issue", value: "Kigali" },
    { label: "Travel plans", value: "Within 1–2 months" },
    { label: "Notes from client", value: "—" },
  ],
  history: [
    { timestamp: "23 May 14:32", body: "Payment received RWF 15,000 (MoMo)" },
    { timestamp: "22 May 18:40", body: "Client replaced passport photo" },
    { timestamp: "20 May 09:25", body: "Status → In progress (by Aline M.)" },
    { timestamp: "20 May 09:00", body: "Assigned to Aline M." },
    { timestamp: "19 May 14:32", body: "Application received" },
  ],
  checklist: [
    {
      id: "step-1",
      label: "Verify client identity against national ID",
      sublabel: "Name + DOB match passport bio page",
      doneAt: "19 May",
      isDone: true,
      isCurrent: false,
    },
    {
      id: "step-2",
      label: "Confirm fee with client",
      sublabel: "RWF 15,000 confirmed via WhatsApp",
      doneAt: "20 May",
      isDone: true,
      isCurrent: false,
    },
    {
      id: "step-3",
      label: "Collect payment",
      sublabel: "RWF 15,000 · MTN MoMo · paid 23 May",
      doneAt: "23 May",
      isDone: true,
      isCurrent: false,
    },
    {
      id: "step-4",
      label: "Review re-uploaded passport photo",
      sublabel: "Client uploaded new photo 22 May",
      isDone: false,
      isCurrent: true,
    },
    {
      id: "step-5",
      label: "Fill official Immigration renewal form",
      sublabel: "Form IMM-04 · use verified details",
      isDone: false,
      isCurrent: false,
    },
    {
      id: "step-6",
      label: "Submit to Department of Immigration",
      sublabel: "Then set status → Submitted to authority",
      isDone: false,
      isCurrent: false,
    },
    {
      id: "step-7",
      label: "Book biometric appointment",
      sublabel: "Notify client of date + what to bring",
      isDone: false,
      isCurrent: false,
    },
    {
      id: "step-8",
      label: "Collect & hand over passport",
      sublabel: "Then set status → Completed",
      isDone: false,
      isCurrent: false,
    },
  ],
  conversation: [
    {
      id: "sys-1",
      type: "system",
      senderName: "System",
      senderInitials: "SY",
      body: "Application submitted",
      timestamp: "19 May 14:32",
    },
    {
      id: "msg-1",
      type: "client",
      senderName: "Aline Kabera",
      senderInitials: "AK",
      body: "Hi, I've sent everything. Let me know if you need anything else!",
      timestamp: "19 May 15:10",
      isRead: true,
    },
    {
      id: "msg-2",
      type: "agent",
      senderName: "Aline M.",
      senderInitials: "AM",
      body: "Got it, thanks! Everything looks good. One thing — your passport photo is a little dark. Could you retake it near a window?",
      timestamp: "20 May 09:24",
      isRead: true,
    },
    {
      id: "note-1",
      type: "internal_note",
      senderName: "Aline M.",
      senderInitials: "AM",
      body: "Photo brightness below threshold. Asked client to retake. Don't submit until fixed.",
      timestamp: "20 May 09:25",
    },
    {
      id: "msg-3",
      type: "client",
      senderName: "Aline Kabera",
      senderInitials: "AK",
      body: "Done! Just uploaded a new one 📸",
      timestamp: "22 May 18:40",
      isRead: true,
    },
    {
      id: "sys-2",
      type: "system",
      senderName: "System",
      senderInitials: "SY",
      body: "Client replaced \"passport photo\" · 22 May 18:40",
      timestamp: "22 May 18:40",
    },
  ],
  documents: [
    {
      id: "doc-1",
      filename: "passport-bio.jpg",
      label: "Current passport",
      fileSize: "1.2 MB",
      uploadedAt: "19 May",
      status: "verified",
    },
    {
      id: "doc-2",
      filename: "id-front.jpg",
      label: "National ID (front)",
      fileSize: "980 KB",
      uploadedAt: "19 May",
      status: "verified",
    },
    {
      id: "doc-3",
      filename: "id-back.jpg",
      label: "National ID (back)",
      fileSize: "1.1 MB",
      uploadedAt: "19 May",
      status: "verified",
    },
    {
      id: "doc-4",
      filename: "photo-v2.jpg",
      label: "Passport photo (v2)",
      fileSize: "2.4 MB",
      uploadedAt: "22 May",
      status: "new",
    },
  ],
};

// ─── Document QC (photo-v2.jpg) ───────────────────────────────────────────────

export const MOCK_DOC_QC = [
  { id: "qc-1", label: "Brightness OK", sublabel: "was too dark before", state: "pass" as const },
  { id: "qc-2", label: "Sharpness OK", sublabel: "no blur detected", state: "pass" as const },
  { id: "qc-3", label: "Face detected, centered", sublabel: "", state: "pass" as const },
  { id: "qc-4", label: "Background not pure white", sublabel: "borderline", state: "warn" as const },
];

// ─── Performance Metrics ──────────────────────────────────────────────────────

export const MOCK_METRICS: AgentMetrics = {
  completedCount: 11,
  completedDelta: "↑ 3 vs April",
  avgTurnaround: 5.2,
  avgTurnaroundDelta: "↓ 0.8d — faster",
  onTimeSLAPercent: 92,
  clientRating: 4.8,
  ratingsCount: 23,
  weeklyBars: [
    { week: "W14", count: 2 },
    { week: "W15", count: 3 },
    { week: "W16", count: 2 },
    { week: "W17", count: 4 },
    { week: "W18", count: 3 },
    { week: "W19", count: 5, isCurrent: true },
  ],
  leaderboard: [
    { initials: "CN", name: "Claudine N.", count: 15, isMe: false },
    { initials: "PM", name: "Patrick M.", count: 13, isMe: false },
    { initials: "AM", name: "Aline M.", count: 11, isMe: true },
    { initials: "DI", name: "Diane I.", count: 9, isMe: false },
    { initials: "TG", name: "Thierry G.", count: 7, isMe: false },
  ],
};

// ─── Settings ─────────────────────────────────────────────────────────────────

export const MOCK_AGENT_SETTINGS: AgentSettings = {
  acceptNewCases: true,
  dailyCap: 8,
  notifications: {
    newCaseAssigned: true,
    clientReplied: true,
    slaApproaching: true,
    dailySummary: false,
  },
  appearance: {
    darkMode: false,
    compactTables: true,
  },
  security: {
    twoFactorEnabled: true,
    trustedDevicesCount: 2,
    passwordLastChangedLabel: "3 months ago",
  },
};

// ─── Stat tiles helper ────────────────────────────────────────────────────────

export function getAgentStats(cases: AgentCase[]) {
  const actionRequired = cases.filter((c) => c.status === "action-required").length;
  const inProgress = cases.filter((c) => c.status === "in-progress").length;
  const awaitingAuthority = cases.filter((c) => c.status === "awaiting-response" || c.status === "submitted-to-authority").length;
  const doneThisWeek = cases.filter((c) => c.status === "completed").length;
  const overSLA = cases.filter((c) => c.slaState === "over").length;

  return { actionRequired, inProgress, awaitingAuthority, doneThisWeek, overSLA };
}
