import type {
  AdminUser,
  AdminAgent,
  AdminMetric,
  WeeklyBar,
  ServiceMixBar,
  PaymentMixBar,
  StatusBreakdown,
  AlertItem,
  ServiceRow,
  FieldDef,
  PricingRow,
  AuditEntry,
  OversightCase,
  BroadcastRecord,
  AdminSettings,
} from "@/lib/types/admin";

export const MOCK_ADMIN_USER: AdminUser = {
  id: "adm-001",
  fullName: "Amara Nwosu",
  firstName: "Amara",
  initials: "AN",
  email: "amara@proxiserve.rw",
  role: "OWNER",
  lastLogin: "2026-06-09T07:42:00Z",
};

export const MOCK_ADMIN_AGENTS: AdminAgent[] = [
  {
    id: "agt-001",
    fullName: "Jean-Paul Hakizimana",
    initials: "JH",
    email: "jphakizimana@proxiserve.rw",
    skills: ["Passport", "NID", "Driver's Licence"],
    load: 6,
    capacity: 10,
    twoFa: true,
    role: "LEAD",
    status: "active",
    activeCases: 6,
    completedTotal: 142,
    avgTurnaround: "1.8d",
    slaPercent: 96,
    rating: 4.8,
  },
  {
    id: "agt-002",
    fullName: "Claudine Uwimana",
    initials: "CU",
    email: "cuwimana@proxiserve.rw",
    skills: ["Passport", "Birth Certificate"],
    load: 9,
    capacity: 10,
    twoFa: true,
    role: "SENIOR",
    status: "active",
    activeCases: 9,
    completedTotal: 98,
    avgTurnaround: "2.1d",
    slaPercent: 91,
    rating: 4.5,
  },
  {
    id: "agt-003",
    fullName: "Théodore Ntawuruhunga",
    initials: "TN",
    email: "tntawuruhunga@proxiserve.rw",
    skills: ["NID", "Tax Clearance"],
    load: 4,
    capacity: 10,
    twoFa: false,
    role: "AGENT",
    status: "active",
    activeCases: 4,
    completedTotal: 67,
    avgTurnaround: "2.6d",
    slaPercent: 88,
    rating: 4.2,
  },
  {
    id: "agt-004",
    fullName: "Solange Mukamana",
    initials: "SM",
    email: "smukamana@proxiserve.rw",
    skills: ["Marriage Certificate", "Birth Certificate"],
    load: 3,
    capacity: 8,
    twoFa: true,
    role: "AGENT",
    status: "away",
    activeCases: 3,
    completedTotal: 44,
    avgTurnaround: "3.0d",
    slaPercent: 83,
    rating: 4.0,
  },
  {
    id: "agt-005",
    fullName: "Olivier Bigirimana",
    initials: "OB",
    email: "obigirimana@proxiserve.rw",
    skills: ["Passport", "NID", "Tax Clearance", "Driver's Licence"],
    load: 7,
    capacity: 10,
    twoFa: true,
    role: "SENIOR",
    status: "active",
    activeCases: 7,
    completedTotal: 119,
    avgTurnaround: "1.9d",
    slaPercent: 94,
    rating: 4.7,
  },
  {
    id: "agt-006",
    fullName: "Beata Nyiransabimana",
    initials: "BN",
    email: "bnyiransabimana@proxiserve.rw",
    skills: ["NID"],
    load: 0,
    capacity: 8,
    twoFa: false,
    role: "AGENT",
    status: "offline",
    activeCases: 0,
    completedTotal: 12,
    avgTurnaround: "3.4d",
    slaPercent: 75,
    rating: 3.8,
  },
];

export const MOCK_KPI_METRICS: AdminMetric[] = [
  {
    id: "apps",
    label: "Applications",
    value: "1,248",
    delta: "+14% vs last month",
    deltaDir: "up",
    deltaColor: "ok",
  },
  {
    id: "completed",
    label: "Completed",
    value: "1,071",
    delta: "+11% vs last month",
    deltaDir: "up",
    deltaColor: "ok",
  },
  {
    id: "revenue",
    label: "Revenue",
    value: "RWF 8.4M",
    delta: "+18% vs last month",
    deltaDir: "up",
    deltaColor: "ok",
  },
  {
    id: "turnaround",
    label: "Avg Turnaround",
    value: "2.1d",
    delta: "−0.3d improvement",
    deltaDir: "down",
    deltaColor: "ok",
  },
  {
    id: "sla",
    label: "SLA On-time",
    value: "93%",
    delta: "−2% vs last month",
    deltaDir: "down",
    deltaColor: "warn",
  },
  {
    id: "rejection",
    label: "Rejection Rate",
    value: "4.8%",
    delta: "+0.6% vs last month",
    deltaDir: "up",
    deltaColor: "warn",
  },
];

export const MOCK_WEEKLY_BARS: WeeklyBar[] = [
  { week: "Apr 7", count: 98 },
  { week: "Apr 14", count: 112 },
  { week: "Apr 21", count: 105 },
  { week: "Apr 28", count: 134 },
  { week: "May 5", count: 118 },
  { week: "May 12", count: 141 },
  { week: "May 19", count: 129 },
  { week: "May 26", count: 156 },
  { week: "Jun 2", count: 148 },
  { week: "Jun 9", count: 107 },
];

export const MOCK_SERVICE_MIX: ServiceMixBar[] = [
  { service: "Passport Renewal", pct: 34, color: "var(--brand)" },
  { service: "National ID", pct: 28, color: "var(--info)" },
  { service: "Driver's Licence", pct: 18, color: "var(--ok)" },
  { service: "Birth Certificate", pct: 12, color: "var(--warn)" },
  { service: "Other", pct: 8, color: "var(--ink-subtle)" },
];

export const MOCK_PAYMENT_MIX: PaymentMixBar[] = [
  { method: "MTN MoMo", pct: 48, color: "var(--warn)" },
  { method: "Airtel Money", pct: 27, color: "var(--danger)" },
  { method: "Card", pct: 16, color: "var(--info)" },
  { method: "Cash (Agent)", pct: 9, color: "var(--ink-subtle)" },
];

export const MOCK_STATUS_BREAKDOWN: StatusBreakdown[] = [
  { label: "Completed", count: 1071, pct: 86, color: "var(--ok)" },
  { label: "In-progress", count: 112, pct: 9, color: "var(--info)" },
  { label: "Awaiting client", count: 45, pct: 4, color: "var(--warn)" },
  { label: "Rejected", count: 20, pct: 1.6, color: "var(--danger)" },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "alert-001",
    message: "Claudine Uwimana is at 90% capacity — consider redistributing 2 cases",
    severity: "warn",
    cta: "View agent",
    ctaHref: "/admin/pricing",
  },
  {
    id: "alert-002",
    message: "SLA breach on APP-2041 (Passport Renewal) — 1.5 days overdue",
    severity: "danger",
    cta: "View case",
    ctaHref: "/admin/oversight",
  },
  {
    id: "alert-003",
    message: "2 agents have not enabled 2FA — enforcement policy requires it",
    severity: "warn",
    cta: "Manage agents",
    ctaHref: "/admin/pricing",
  },
  {
    id: "alert-004",
    message: "Dispute opened on APP-1998 by client Murekatete Cynthia",
    severity: "danger",
    cta: "View dispute",
    ctaHref: "/admin/oversight",
  },
];

export const MOCK_SERVICES: ServiceRow[] = [
  {
    id: "svc-001",
    name: "Passport Renewal",
    category: "Identity",
    fee: 50000,
    eta: "5–7 days",
    schemaVersion: "v3",
    volume30d: 428,
    status: "active",
  },
  {
    id: "svc-002",
    name: "National ID Card",
    category: "Identity",
    fee: 15000,
    eta: "3–5 days",
    schemaVersion: "v2",
    volume30d: 351,
    status: "active",
  },
  {
    id: "svc-003",
    name: "Driver's Licence",
    category: "Transport",
    fee: 35000,
    eta: "7–10 days",
    schemaVersion: "v2",
    volume30d: 224,
    status: "active",
  },
  {
    id: "svc-004",
    name: "Birth Certificate",
    category: "Civil Records",
    fee: 10000,
    eta: "2–4 days",
    schemaVersion: "v1",
    volume30d: 150,
    status: "active",
  },
  {
    id: "svc-005",
    name: "Marriage Certificate",
    category: "Civil Records",
    fee: 20000,
    eta: "4–6 days",
    schemaVersion: "v1",
    volume30d: 89,
    status: "active",
  },
  {
    id: "svc-006",
    name: "Tax Clearance Letter",
    category: "Finance",
    fee: 25000,
    eta: "3–4 days",
    schemaVersion: "v1",
    volume30d: 66,
    status: "active",
  },
  {
    id: "svc-007",
    name: "Residency Certificate",
    category: "Identity",
    fee: 12000,
    eta: "2–3 days",
    schemaVersion: "v1-draft",
    volume30d: 0,
    status: "draft",
  },
  {
    id: "svc-008",
    name: "Death Certificate",
    category: "Civil Records",
    fee: 8000,
    eta: "3–5 days",
    schemaVersion: "v1",
    volume30d: 0,
    status: "inactive",
  },
];

export const MOCK_SCHEMA_FIELDS: FieldDef[] = [
  {
    id: "f-001",
    label: "Full name",
    type: "short-text",
    required: true,
    conditional: false,
    isNew: false,
  },
  {
    id: "f-002",
    label: "Date of birth",
    type: "date",
    required: true,
    conditional: false,
    isNew: false,
  },
  {
    id: "f-003",
    label: "Current NID number",
    type: "short-text",
    required: true,
    conditional: false,
    isNew: false,
  },
  {
    id: "f-004",
    label: "Reason for renewal",
    type: "single-choice",
    required: true,
    conditional: false,
    isNew: false,
    options: ["Expired", "Lost", "Damaged", "Name change"],
  },
  {
    id: "f-005",
    label: "Supporting document",
    type: "document",
    required: false,
    conditional: true,
    isNew: false,
    helpText: "Required if reason is Lost or Damaged",
  },
  {
    id: "f-006",
    label: "Phone number",
    type: "phone",
    required: true,
    conditional: false,
    isNew: true,
  },
];

export const MOCK_PRICING_ROWS: PricingRow[] = [
  {
    id: "pr-001",
    service: "Passport Renewal",
    standardFee: 50000,
    urgentFee: 75000,
    govFeePassthrough: true,
    effectiveDate: "2026-01-01",
    scheduledChange: {
      newStandardFee: 55000,
      newUrgentFee: 82500,
      effectiveDate: "2026-07-01",
    },
  },
  {
    id: "pr-002",
    service: "National ID Card",
    standardFee: 15000,
    urgentFee: 22500,
    govFeePassthrough: true,
    effectiveDate: "2026-01-01",
  },
  {
    id: "pr-003",
    service: "Driver's Licence",
    standardFee: 35000,
    urgentFee: 52500,
    govFeePassthrough: true,
    effectiveDate: "2026-01-01",
  },
  {
    id: "pr-004",
    service: "Birth Certificate",
    standardFee: 10000,
    urgentFee: 15000,
    govFeePassthrough: false,
    effectiveDate: "2026-01-01",
  },
  {
    id: "pr-005",
    service: "Marriage Certificate",
    standardFee: 20000,
    urgentFee: 30000,
    govFeePassthrough: false,
    effectiveDate: "2026-01-01",
  },
  {
    id: "pr-006",
    service: "Tax Clearance Letter",
    standardFee: 25000,
    urgentFee: 37500,
    govFeePassthrough: true,
    effectiveDate: "2026-01-01",
  },
  {
    id: "pr-007",
    service: "Residency Certificate",
    standardFee: 12000,
    urgentFee: 18000,
    govFeePassthrough: false,
    effectiveDate: "2026-07-01",
  },
  {
    id: "pr-008",
    service: "Death Certificate",
    standardFee: 8000,
    urgentFee: 12000,
    govFeePassthrough: false,
    effectiveDate: "2026-01-01",
  },
];

export const MOCK_AUDIT_LOG: AuditEntry[] = [
  {
    id: "au-020",
    timestamp: "2026-06-09T09:14:22Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Updated Passport Renewal standard fee: RWF 50,000 → 55,000 (effective 2026-07-01)",
    kind: "Money",
  },
  {
    id: "au-019",
    timestamp: "2026-06-09T08:50:11Z",
    actor: "System",
    actorType: "system",
    description: "SLA breach auto-flagged on APP-2041 (Passport Renewal, assigned to Claudine Uwimana)",
    kind: "Assignment",
  },
  {
    id: "au-018",
    timestamp: "2026-06-08T16:33:07Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Intervened on case APP-1998 — reason: Client dispute escalation. Agent Jean-Paul Hakizimana notified",
    kind: "Privileged",
  },
  {
    id: "au-017",
    timestamp: "2026-06-08T15:20:44Z",
    actor: "Jean-Paul Hakizimana",
    actorType: "agent",
    description: "Case APP-2029 status changed: In-progress → Completed",
    kind: "Assignment",
  },
  {
    id: "au-016",
    timestamp: "2026-06-08T14:05:31Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Published National ID Card schema v2 — automatic migration applied to 142 drafts",
    kind: "Config",
  },
  {
    id: "au-015",
    timestamp: "2026-06-08T11:47:19Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Invited new agent: Beata Nyiransabimana (bnyiransabimana@proxiserve.rw)",
    kind: "Assignment",
  },
  {
    id: "au-014",
    timestamp: "2026-06-07T17:22:03Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Broadcast sent to All clients (1,180 recipients) via WhatsApp + Email",
    kind: "Config",
  },
  {
    id: "au-013",
    timestamp: "2026-06-07T16:10:55Z",
    actor: "System",
    actorType: "system",
    description: "Scheduled price change reminder: Passport Renewal fee increases on 2026-07-01",
    kind: "Money",
  },
  {
    id: "au-012",
    timestamp: "2026-06-07T14:30:28Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Session timeout policy updated: 8h → 4h",
    kind: "Config",
  },
  {
    id: "au-011",
    timestamp: "2026-06-06T10:15:44Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Refund issued for APP-1872: RWF 50,000 to client Karangwa Patrick",
    kind: "Money",
  },
  {
    id: "au-010",
    timestamp: "2026-06-06T09:00:00Z",
    actor: "System",
    actorType: "system",
    description: "Scheduled maintenance window completed — 14m downtime",
    kind: "Config",
  },
  {
    id: "au-009",
    timestamp: "2026-06-05T18:45:12Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Permanently deleted service 'Legacy ID (Old)' after 30-day archive period",
    kind: "Privileged",
  },
  {
    id: "au-008",
    timestamp: "2026-06-05T14:22:37Z",
    actor: "Claudine Uwimana",
    actorType: "agent",
    description: "Case APP-2011 payment collected in-person (cash): RWF 35,000",
    kind: "Money",
  },
  {
    id: "au-007",
    timestamp: "2026-06-04T11:05:09Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "2FA enforcement enabled for all staff accounts",
    kind: "Config",
  },
  {
    id: "au-006",
    timestamp: "2026-06-03T16:50:22Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Guest application setting disabled — clients must have accounts",
    kind: "Config",
  },
  {
    id: "au-005",
    timestamp: "2026-06-02T09:30:14Z",
    actor: "System",
    actorType: "system",
    description: "Monthly revenue report auto-generated: RWF 8.4M (Jun 2026)",
    kind: "Money",
  },
  {
    id: "au-004",
    timestamp: "2026-06-01T15:17:44Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Residency Certificate service created (status: Draft)",
    kind: "Config",
  },
  {
    id: "au-003",
    timestamp: "2026-05-31T13:44:02Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Théodore Ntawuruhunga role changed: AGENT → SENIOR",
    kind: "Privileged",
  },
  {
    id: "au-002",
    timestamp: "2026-05-30T10:22:18Z",
    actor: "Amara Nwosu",
    actorType: "admin",
    description: "Driver's Licence urgent fee updated: RWF 45,000 → 52,500",
    kind: "Money",
  },
  {
    id: "au-001",
    timestamp: "2026-05-29T09:00:00Z",
    actor: "System",
    actorType: "system",
    description: "ProxiServe Admin Panel activated — initial configuration complete",
    kind: "Config",
  },
];

export const MOCK_OVERSIGHT_CASES: OversightCase[] = [
  {
    code: "APP-2041",
    service: "Passport Renewal",
    agent: "Claudine Uwimana",
    client: "Habimana Eric",
    status: "sla-breach",
    issue: "1.5 days overdue",
  },
  {
    code: "APP-1998",
    service: "Birth Certificate",
    agent: "Jean-Paul Hakizimana",
    client: "Murekatete Cynthia",
    status: "disputed",
    issue: "Client disputes document fee",
  },
  {
    code: "APP-2038",
    service: "National ID Card",
    agent: "Théodore Ntawuruhunga",
    client: "Nkurunziza Fabrice",
    status: "in-progress",
  },
  {
    code: "APP-2031",
    service: "Driver's Licence",
    agent: "Olivier Bigirimana",
    client: "Uwase Diane",
    status: "in-progress",
  },
  {
    code: "APP-2025",
    service: "Passport Renewal",
    agent: "Jean-Paul Hakizimana",
    client: "Ishimwe Yves",
    status: "escalated",
    issue: "Documents returned unprocessed",
  },
  {
    code: "APP-2019",
    service: "Tax Clearance Letter",
    agent: "Olivier Bigirimana",
    client: "Karangwa Patrick",
    status: "in-progress",
  },
  {
    code: "APP-2017",
    service: "Marriage Certificate",
    agent: "Solange Mukamana",
    client: "Ndayisaba Gentille",
    status: "sla-breach",
    issue: "0.8 days overdue",
  },
  {
    code: "APP-2014",
    service: "National ID Card",
    agent: "Claudine Uwimana",
    client: "Mutoni Beatrice",
    status: "in-progress",
  },
  {
    code: "APP-2010",
    service: "Birth Certificate",
    agent: "Théodore Ntawuruhunga",
    client: "Rwigema Jean",
    status: "in-progress",
  },
  {
    code: "APP-1989",
    service: "Passport Renewal",
    agent: "Jean-Paul Hakizimana",
    client: "Nzeyimana Gloria",
    status: "disputed",
    issue: "Payment amount disputed",
  },
  {
    code: "APP-1978",
    service: "Driver's Licence",
    agent: "Olivier Bigirimana",
    client: "Tuyishime Alain",
    status: "resolved",
  },
  {
    code: "APP-1965",
    service: "National ID Card",
    agent: "Claudine Uwimana",
    client: "Ingabire Sandra",
    status: "resolved",
  },
];

export const MOCK_BROADCASTS: BroadcastRecord[] = [
  {
    id: "bc-005",
    audience: "All clients",
    channels: ["whatsapp", "email"],
    message: "ProxiServe offices will be closed on Monday 10 June for the public holiday. Applications submitted will be processed from Tuesday.",
    sentAt: "2026-06-07T17:22:03Z",
    reach: 1180,
  },
  {
    id: "bc-004",
    audience: "Clients with pending applications",
    channels: ["sms"],
    message: "Reminder: Your application is awaiting your response. Please log in to complete the required steps.",
    sentAt: "2026-06-03T10:00:00Z",
    reach: 87,
  },
  {
    id: "bc-003",
    audience: "All agents",
    channels: ["in-app", "email"],
    message: "New SLA policy effective 2026-07-01: Passport Renewal target reduced from 7 to 5 days.",
    sentAt: "2026-05-28T14:30:00Z",
    reach: 6,
  },
  {
    id: "bc-002",
    audience: "All clients",
    channels: ["whatsapp", "sms", "email"],
    message: "We have extended our service hours. You can now submit applications until 8 PM on weekdays.",
    sentAt: "2026-05-15T09:00:00Z",
    reach: 1042,
  },
  {
    id: "bc-001",
    audience: "Clients with completed applications",
    channels: ["email"],
    message: "Thank you for using ProxiServe! Please take 2 minutes to rate your experience.",
    sentAt: "2026-05-01T10:00:00Z",
    reach: 320,
  },
];

export const MOCK_ADMIN_SETTINGS: AdminSettings = {
  acceptNewApps: true,
  guestApps: false,
  dataRetention: "24-months",
  compactTables: false,
  enforce2FA: true,
  sessionTimeout: 240,
  ipAllowlist: "",
  maintenanceMode: false,
};
